ProyectoA1/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # incluimos las urls de la AppDepartamento
    re_path('', include('applications.departamento.urls')),
    # incluimos las urls de la AppEmpleado
    re_path('', include('applications.empleado.urls')),
    # incluimos las urls de la home
    re_path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/urls.py
from django.urls import path

from . import views

app_name = "Departamento_App"

urlpatterns = [
    path('NuevoDepartamento/', views.NewDepartamentoView.as_view(), name='NuevoDepartamento'),
    path('ListaDepartamentos/', views.DepartamentoListView.as_view(), name='TodosLosDepartamentos'),
    path('DetalleDepartamento/<pk>/', views.DepartamentoListView.as_view(), name='DetalleDepartamento'),
]

applications/empleado/urls.py
from django.urls import path

from . import views

app_name = "Empleado_App"

urlpatterns = [
    path('', views.IndexEmpleadoView.as_view(), name="Index"),
    # List
    path('ListaEmpleados/', views.ListAllEmpleados.as_view(), name="TodosLosEmpleados"),
    path('ListaEmpleadosPorArea/<NameDepto>/', views.ListEmpleadosByDepartamento.as_view(), name="EmpleadosPorArea"),
    path('VerEmpleado/<pk>/', views.EmpleadoDetailView.as_view(), name="DetalleEmpleado"),
    # Operations CRUD
    path('success/', views.successEmpleado.as_view(), name='Correcto'),
    path('RegistrarEmpleado/', views.AddEmpleadoCreateView.as_view(), name="RegistrarEmpleado"),
    path('ActualizarEmpleado/<pk>/', views.EmpleadoUpdateView.as_view(), name='ActualizarEmpleado'),
    path('BorrarEmpleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='BorrarEmpleado'),

]

templates/includes/header.html
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>

      <li class="menu-text">Empleados</li>

      <li><a href="{% url 'Empleado_App:TodosLosEmpleados'  %}">Listar</a></li>
      <li><a href="{% url 'Departamento_App:TodosLosDepartamentos'  %}">Departamentos</a>
         <ul class="submenu menu vertical" data-submenu>
          <li><a href="{% url 'Departamento_App:NuevoDepartamento'  %}">Nuevo Departamento</a></li>
        </ul>
      </li>

    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="Buscar Empleado"></li>
      <li><a class="button" href="{% url 'Empleado_App:RegistrarEmpleado' %}">Registrar Nuevo</a></li>
    </ul>
  </div>
</div>