ProyectoA1/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # incluimos las urls de la AppDepartamento
    re_path('', include('applications.departamento.urls')),
    # incluimos las urls de la AppEmpleado
    re_path('', include('applications.empleado.urls')),
    # incluimos las urls de la home
    re_path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/urls.py
from django.urls import path

from . import views

app_name = "Departamento_App"

urlpatterns = [
    path('NuevoDepartamento/', views.NewDepartamentoView.as_view(), name='NuevoDepartamento'),
    path('ListaDepartamentos/', views.DepartamentoListView.as_view(), name='TodosLosDepartamentos'),
    path('DetalleDepartamento/<pk>/', views.DepartamentoListView.as_view(), name='DetalleDepartamento'),
]

applications/departamento/models.py
from django.db import models

# Create your models here.

class Departamento(models.Model):
    name = models.CharField('nombre',max_length=50, unique=True)
    short_name = models.CharField('nombre_corto', max_length=20, blank=True, unique=True)
    anulate = models.BooleanField('anulado',default=False)

    class Meta:
        verbose_name = "Departamento"
        verbose_name_plural = "Departamentos"
        ordering = ['id']
        unique_together = ('name', 'short_name')

    def __str__(self):
        return str(self.id) + ' - ' + self.name + ' ' + self.short_name

applications/departamento/forms.py
from django import forms

from applications.empleado.models import Empleado


class NewDepartamentoForm(forms.Form):
    nombre_Empleado = forms.CharField(max_length=50)
    apellidos_Empleado = forms.CharField(max_length=50)
    nombre_Departamento = forms.CharField(max_length=50)
    ShorName_Departamento = forms.CharField(max_length=50)

applications/departamento/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

# Create your views here.
from django.views.generic.edit import FormView
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    TemplateView,
)

# Formularios
from .forms import NewDepartamentoForm

# Modelos
from applications.empleado.models import Empleado
from .models import Departamento


# Create your views here.

# List View
class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/list_all.html"
    paginate_by = 5
    context_object_name = "listDepartamentos"

    def get_queryset(self):
        busqueda = self.request.GET.get('keyword', '')
        lista = Departamento.objects.filter(
            name__icontains=busqueda,
        )
        return lista


class NewDepartamentoView(FormView):
    template_name = "departamento/NewDepartamento.html"
    form_class = NewDepartamentoForm
    success_url = reverse_lazy('Departamento_App:TodosLosDepartamentos')

    def form_valid(self, form):
        # Logic Process
        nombre_Empleado = form.cleaned_data['nombre_Empleado']
        apellidos_Empleado = form.cleaned_data['apellidos_Empleado']

        depto = Departamento(
            name=form.cleaned_data['nombre_Departamento'],
            short_name=form.cleaned_data['ShorName_Departamento']
        )
        depto.save()

        Empleado.objects.create(
            firts_name=nombre_Empleado,
            last_name=apellidos_Empleado,
            job='1',
            departamento=depto
        )

        return super(NewDepartamentoView, self).form_valid(form)

templates/departamento/NewDepartamento.html
{% extends 'base.html' %}

{% load static%}

{% block title %} Agregar Empleado{% endblock title %}

{% block cuerpo %}
    {% include "includes/header.html" %}

    <!-- BLOQUE DE REGISTRO-->
    <div class="grid-container">
        <form action="" method="post">{% csrf_token %}
            <div class="grid-x grid-padding-x">
                <h3 class="cell">Datos Empleado</h3>
                <div class="medium-6 cell">
                    <label>Nombre Empleado:
                        {{ form.nombre_Empleado }}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Apellido Empleado:
                        {{ form.apellidos_Empleado }}
                    </label>
                </div>
            </div>
            <div class="grid-x grid-padding-x">
            <h3 class="cell">Datos Departamento</h3>
                <div class="medium-6 cell">
                    <label>Nombre Departamento:
                        {{ form.nombre_Departamento }}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Nombre corto departamento:
                        {{ form.ShorName_Departamento }}
                    </label>
                </div>
            </div>
                <input class="cell button" type="submit" value="Agregar">
        </form>
    </div>
    <!-- FIN BLOQUE DE REGISTRO -->
{% endblock cuerpo %}

templates/departamento/list_all.html
{% extends 'base.html' %}

{% load static%}

{% block title %}Lista Departamentos{% endblock title %}

{% block cuerpo %}
    {% include "includes/header.html" %}<!-- BLOQUE GENERAL -->
    <div class="grid-container">
        <div class="grid-x">
            <!-- BLOQUE DE BIENVENIDA -->
            <h1 class="cell">Todos los Departamentos</h1>
            <!--BUSQUIEDA-->
            <div class="cell grid-x">
                <form action="" method="get">{% csrf_token %}
                    <div class="large-6'">
                        <input type="text" name="keyword" id="keyword" placeholder="BuscarEmpleado">
                    </div>
                    <div class="large-2">
                        <input class="button" type="submit" value="BUSCAR">
                    </div>
                </form>
            </div>
            <!--FIN BUSQUIEDA-->
            <!--TABLA-->
            <div class="cell">
                <table>
                    <thead>
                        <td>ID</td>
                        <td>Nombre</td>
                        <td>Nombre Corto</td>
                        <td>Accion</td>
                    </thead>
                    <tbody>
                        {% for x in listDepartamentos %}
                        <tr>
                            <td>{{ x.id }}</td>
                            <td>{{ x.name }}</td>
                            <td>{{ x.short_name }}</td>
                            <td>
                                <a class="button success" href="{% url 'Departamento_App:DetalleDepartamento' x.id %}" >Ver Empleados</a>
                                <a class="button warning" >Actualizar</a>
                                <a class="button alert" >Borrar</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <!--FIN TABLA-->
            <!--PAGINACION-->
            <div class="cell">
                {% if is_paginated %}
                    <nav aria-label="Pagination">
                        <ul class="pagination text-center">
                            {% if page_obj.has_previous %}
                                <li class="pagination-previous"><a href="?page={{page_obj.previous_page_number}}" aria-label="Previous page">Anterior</a></li>
                            {% else %}
                                <li class="pagination-previous disabled">Anterior</li>
                            {% endif %}

                            {% for x in paginator.page_range %}
                                {% if page_obj.number == x %}
                                    <li class="current"><span class="show-for-sr">You're on page</span>{{ x }}</li>
                                {% else %}
                                    <li><a href="?page={{x}}" aria-label="Page {{x}}">{{x}}</a></li>
                                {% endif %}
                            {% endfor %}

                            {% if page_obj.has_next %}
                                <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Siguiente</a></li>
                            {% else %}
                                <li class="pagination-next disabled">Siguiente</li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            </div>
            <!-- FINPAGINACION-->
        </div>
    </div>
    <!-- FIN BLOQUE GENERAL -->
{% endblock cuerpo %}