ProyectoA1/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # incluimos las urls de la AppDepartamento
    re_path('', include('applications.departamento.urls')),
    # incluimos las urls de la AppEmpleado
    re_path('', include('applications.empleado.urls')),
    # incluimos las urls de la home
    re_path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/empleado/urls.py
from django.urls import path

from . import views

app_name = "Empleado_App"

urlpatterns = [
    path('', views.IndexEmpleadoView.as_view(), name="Index"),
    # List
    path('ListaEmpleados/', views.ListAllEmpleados.as_view(), name="TodosLosEmpleados"),
    path('ListaEmpleadosPorArea/<NameDepto>/', views.ListEmpleadosByDepartamento.as_view(), name="EmpleadosPorArea"),
    path('VerEmpleado/<pk>/', views.EmpleadoDetailView.as_view(), name="DetalleEmpleado"),
    # Operations CRUD
    path('success/', views.successEmpleado.as_view(), name='Correcto'),
    path('RegistrarEmpleado/', views.AddEmpleadoCreateView.as_view(), name="RegistrarEmpleado"),
    path('ActualizarEmpleado/<pk>/', views.EmpleadoUpdateView.as_view(), name='ActualizarEmpleado'),
    path('BorrarEmpleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='BorrarEmpleado'),

]

applications/empleado/models.py
from django.db import models
from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField


# Create your models here.


class Habilidad(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)
    
    
    class Meta:
        verbose_name = "Habilidad"
        verbose_name_plural = "Habilidades"

    def __str__(self):
        return self.habilidad


class Empleado(models.Model):

    Job_Choices = (
        ('0', 'Contador'),
        ('1', 'Administrador'),
        ('2', 'Economista'),
        ('3', 'Otro'),
    )

    firts_name = models.CharField('Nombres', max_length=50)
    last_name = models.CharField('Apellidos', max_length=50)
    full_name = models.CharField('Nombre Completo', max_length=100, blank=True)
    job = models.CharField('Trabajo', max_length=1, choices=Job_Choices)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)
    # Relation many to many
    habilidades = models.ManyToManyField(Habilidad)
    hoja_vida = RichTextField(blank=True, null=True)
    
    class Meta:
        verbose_name = "Empleado"
        verbose_name_plural = "Empleados"
        ordering = ['id', 'last_name', 'firts_name']
        unique_together = ('last_name', 'firts_name')

    def __str__(self):
        return self.firts_name +' - '+ self.last_name +' - '+ self.job +' - '+self.get_job_display()

applications/empleado/forms.py
from django import forms

from .models import Empleado


class EmpleadoForm(forms.ModelForm):
    class Meta:
        model = Empleado
        fields = (
            'firts_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',
        )
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()
        }

applications/empleado/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

# Create your views here.

from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView,
)

# Models
from .models import Empleado
# Forms
from .forms import EmpleadoForm


class IndexEmpleadoView(TemplateView):
    """vista que carga la pagina de inicio"""
    template_name = "IndexEmpleado.html"


# GRID DATA
class ListAllEmpleados(ListView):
    template_name = 'empleado/list_all.html'
    model = Empleado
    context_object_name = 'listaEmpleados'
    paginate_by = 7

    def get_queryset(self):
        busqueda = self.request.GET.get('keyword', '')
        lista = Empleado.objects.filter(
            firts_name__icontains=busqueda,
        )
        return lista


# Grid por departamento
class ListEmpleadosByDepartamento(ListView):
    template_name = 'empleado/listByDepartamento.html'
    model = Empleado
    context_object_name = 'listaEmpleados'
    paginate_by = 7

    def get_queryset(self):
        busqueda = self.kwargs['NameDepto']
        lista = Empleado.objects.filter(
            departamento__name=busqueda,
        )
        return lista


# Detail View
class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "empleado/EmpleadoDetailView.html"


# Success Message
class successEmpleado(TemplateView):
    template_name = "empleado/success.html"


# add view
class AddEmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "empleado/AddEmpleado.html"
    #fields = ('__all__')
    form_class = EmpleadoForm
    success_url = reverse_lazy('Empleado_App:TodosLosEmpleados')

    def form_valid(self, form):
        # Logic Process
        empleado = form.save()
        empleado.full_name = empleado.firts_name + ' ' + empleado.last_name
        empleado.save()
        return super(AddEmpleadoCreateView, self).form_valid(form)


class successUpdateEmpleado(TemplateView):
    template_name = "empleado/sucessUpdate.html"


# update view
class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "empleado/UpdateEmpleado.html"
    fields = ('__all__')
    success_url = reverse_lazy('Empleado_App:TodosLosEmpleados')

    # Intercept values of POST
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print(request.POST)
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        # Logic Process
        empleado = form.save()
        empleado.full_name = empleado.firts_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoUpdateView, self).form_valid(form)


# delete view
class EmpleadoDeleteView(DeleteView):
    model = Empleado
    context_object_name = 'EmpleadoAEliminar'
    template_name = "empleado/DeleteEmpleado.html"
    success_url = reverse_lazy('Empleado_App:Correcto')

templates/empleado/AddEmpleado.html
{% extends 'base.html' %}

{% load static%}

{% block title %} Agregar Empleado{% endblock title %}

{% block cuerpo %}
    {% include "includes/header.html" %}
        <!-- BLOQUE DE REGISTRO-->
        <div class="grid-container">
            <div class="grid-x">
            <form class="cell grid-x" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                <div class="medium-6 cell">
                    <label>Nombre:
                        <p>{{ form.firts_name }}</p>
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Apellidos:
                        <p>{{ form.last_name }}</p>
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Trabajo:
                        <p>{{ form.job }}</p>
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>departamento:
                        <p>{{ form.departamento }}</p>
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Avatar:
                        <p>{{ form.avatar }}</p>
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Habilidades:
                        <p>{{ form.habilidades }}</p>
                    </label>
                </div>
                <input class="button cell" type="submit" value="Agregar">
            </form>
        </div>
    </div>
    <!-- FIN BLOQUE DE REGISTRO -->
{% endblock cuerpo %}

templates/empleado/DeleteEmpleado.html
{% extends 'base.html' %}

{% load static%}

{% block title %}Borrar Empleado{% endblock title %}

{% block cuerpo %}
    {% include "includes/header.html" %}
    <!-- BLOQUE de Eliminacion -->
    <div class="grid-container">
        <div class="grid-x align-center">
            <form action="" method="post">{% csrf_token %}
                <p class="cell">Confirme que desea eliminar el Empleado</p>
                <label for="name"><input type="text" name="name" id="name" value="{{ object.firts_name }}" DISABLED></label>
                <input class="cell button alert" type="submit" value="Confirmar">
            </form>
        </div>
    </div>
    <!-- FIN BLOQUE Eliminacion -->
{% endblock cuerpo %}

templates/empleado/EmpleadoDetailView.html
{% extends 'base.html' %}
{% load static%}

{% block title %}Detalle Empleado{% endblock title %}

{% block cuerpo %}
    {% include "includes/header.html" %}
    <div class="grid-container">
        <div class="grid-x">
            <h3 class="cell">Todos los datos</h3>
            <label class="cell" for="name">Nombre:<input type="text" name="name" id="name" disabled value="{{ empleado.firts_name }}"></label>
            <label class="cell" for="last_name">Apellido:<input type="text" name="last_name" id="last_name" disabled value="{{ empleado.last_name }}"></label>
            <label class="cell" for="name_job">Trabajo:<input type="text" name="name_job" id="name_job" disabled value="{{ empleado.get_job_display }}"></label>

            <div class="cell grid-x align-center">
            {% if empleado.avatar %}
                <label class="cell large-2" for="Avatar">Avatar:<img name="Avatar" class="thumbnail" id="Avatar" src="{{empleado.avatar.url}}" alt=""></label>
            {% else %}
                <label class="cell large-2" for="Avatar">Avatar:<img name="Avatar" class="thumbnail" id="Avatar" src="{% static "img/avatarGeneric.png" %}" alt=""></label>
            {% endif %}
            </div>


            <label class="cell" for="depto">Departamento:<input type="text" name="depto" id="depto" disabled value="{{ empleado.departamento.name }}"></label>
            <h3>Habilidades</h3>
            {% for habilidades in empleado.habilidades.all %}
                <ul class="cell">
                    <li>{{ habilidades.habilidad }}</li>
                </ul>
            {% endfor %}


        </div>
    </div>

{% endblock cuerpo %}

templates/empleado/UpdateEmpleado.html
{% extends 'base.html' %}

{% load static%}

{% block title %} Actualizar Empleado{% endblock title %}

{% block cuerpo %}
    {% include "includes/header.html" %}
        <!-- BLOQUE de Registro -->
        <div class="grid-container">
            <div class="grid-x">
            <form class="cell" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                <div class="medium-6 cell">
                    <label>Nombre:
                        <p>{{ form.firts_name }}</p>
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Apellidos:
                        <p>{{ form.last_name }}</p>
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Trabajo:
                        <p>{{ form.job }}</p>
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>departamento:
                        <p>{{ form.departamento }}</p>
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Avatar:
                        <p>{{ form.avatar }}</p>
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Habilidades:
                        <p>{{ form.habilidades }}</p>
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Hoja de vida:
                        <p>{{ form.hoja_vida }}</p>
                    </label>
                </div>
                <input class="button cell" type="submit" value="Actualizar">
            </form>
        </div>
    </div>
    <!-- FIN BLOQUE GENERAL -->
{% endblock cuerpo %}

templates/empleado/listByDepartamento.html
{% extends 'base.html' %}

{% load static%}

{% block title %} Listar Empleados Por Departamento{% endblock title %}

{% block cuerpo %}
    {% include "includes/header.html" %}
    <!-- BLOQUE GENERAL -->
    <div class="grid-container">
        <div class="grid-x">
            <!-- BLOQUE DE BIENVENIDA -->
            <h1 class="cell">Empleados del Departamento:{{ Departamento }}</h1>
            <!--BUSQUIEDA-->
            <div class="cell grid-x">
                <form action="" method="get">{% csrf_token %}
                    <div class="large-6'">
                        <input type="text" name="keyword" id="keyword" placeholder="BuscarEmpleado">
                    </div>
                    <div class="large-2">
                        <input class="button" type="submit" value="BUSCAR">
                    </div>
                </form>
            </div>
            <!--FIN BUSQUIEDA-->
            <!--TABLA-->
            <div class="cell">
                <table>
                    <thead>
                        <td>ID</td>
                        <td>Nombre</td>
                        <td>Apellido</td>
                        <td>Depto</td>
                        <td>Job</td>
                        <td>Accion</td>
                    </thead>
                    <tbody>
                        {% for x in listaEmpleados %}
                        <tr>
                            <td>{{ x.id }}</td>
                            <td>{{ x.firts_name }}</td>
                            <td>{{ x.last_name }}</td>
                            <td>{{ x.departamento.name }}</td>
                            <td>{{ x.get_job_display }}</td>
                            <td>
                                <a class="button success" href="{% url 'Empleado_App:DetalleEmpleado' x.id %}" >Ver</a>
                                <a class="button warning" >Actualizar</a>
                                <a class="button alert" >Borrar</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <!--FIN TABLA-->
            <!--PAGINACION-->
            <div class="cell">
                {% if is_paginated %}
                    <nav aria-label="Pagination">
                        <ul class="pagination text-center">
                            {% if page_obj.has_previous %}
                                <li class="pagination-previous"><a href="?page={{page_obj.previous_page_number}}" aria-label="Previous page">Anterior</a></li>
                            {% else %}
                                <li class="pagination-previous disabled">Anterior</li>
                            {% endif %}

                            {% for x in paginator.page_range %}
                                {% if page_obj.number == x %}
                                    <li class="current"><span class="show-for-sr">You're on page</span>{{ x }}</li>
                                {% else %}
                                    <li><a href="?page={{x}}" aria-label="Page {{x}}">{{x}}</a></li>
                                {% endif %}
                            {% endfor %}

                            {% if page_obj.has_next %}
                                <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Siguiente</a></li>
                            {% else %}
                                <li class="pagination-next disabled">Siguiente</li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            </div>
            <!-- FINPAGINACION-->
        </div>
    </div>
    <!-- FIN BLOQUE GENERAL -->
{% endblock cuerpo %}

templates/empleado/list_all.html
{% extends 'base.html' %}

{% load static%}

{% block title %} Listar Empleados{% endblock title %}

{% block cuerpo %}
    {% include "includes/header.html" %}
    <!-- BLOQUE GENERAL -->
    <div class="grid-container">
        <div class="grid-x">
            <!-- BLOQUE DE BIENVENIDA -->
            <h1 class="cell">Todos los Empleados</h1>
            <!--BUSQUIEDA-->
            <div class="cell grid-x">
                <form action="" method="get">{% csrf_token %}
                    <div class="large-6'">
                        <input type="text" name="keyword" id="keyword" placeholder="BuscarEmpleado">
                    </div>
                    <div class="large-2">
                        <input class="button" type="submit" value="BUSCAR">
                    </div>
                </form>
            </div>
            <!--FIN BUSQUIEDA-->
            <!--TABLA-->
            <div class="cell">
                <table>
                    <thead>
                        <td>ID</td>
                        <td>Nombre</td>
                        <td>Apellido</td>
                        <td>Depto</td>
                        <td>Job</td>
                        <td>Accion</td>
                    </thead>
                    <tbody>
                        {% for x in listaEmpleados %}
                        <tr>
                            <td>{{ x.id }}</td>
                            <td>{{ x.firts_name }}</td>
                            <td>{{ x.last_name }}</td>
                            <td>{{ x.departamento.name }}</td>
                            <td>{{ x.get_job_display }}</td>
                            <td>
                                <a class="button success" href="{% url 'Empleado_App:DetalleEmpleado' x.id %}" >Ver</a>
                                <a class="button warning" href="{% url 'Empleado_App:ActualizarEmpleado' x.id %}" >Actualizar</a>
                                <a class="button alert"  href="{% url 'Empleado_App:BorrarEmpleado' x.id %}">Borrar</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <!--FIN TABLA-->
            <!--PAGINACION-->
            <div class="cell">
                {% if is_paginated %}
                    <nav aria-label="Pagination">
                        <ul class="pagination text-center">
                            {% if page_obj.has_previous %}
                                <li class="pagination-previous"><a href="?page={{page_obj.previous_page_number}}" aria-label="Previous page">Anterior</a></li>
                            {% else %}
                                <li class="pagination-previous disabled">Anterior</li>
                            {% endif %}

                            {% for x in paginator.page_range %}
                                {% if page_obj.number == x %}
                                    <li class="current"><span class="show-for-sr">You're on page</span>{{ x }}</li>
                                {% else %}
                                    <li><a href="?page={{x}}" aria-label="Page {{x}}">{{x}}</a></li>
                                {% endif %}
                            {% endfor %}

                            {% if page_obj.has_next %}
                                <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Siguiente</a></li>
                            {% else %}
                                <li class="pagination-next disabled">Siguiente</li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            </div>
            <!-- FINPAGINACION-->
        </div>
    </div>
    <!-- FIN BLOQUE GENERAL -->
{% endblock cuerpo %}

templates/empleado/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <H1>Se guardo bn</H1>
</body>
</html>